#!/bin/bash

version=$(sed -n 's/ktlint = "\(.*\)"/\1/p' gradle/libs.versions.toml)
url="https://github.com/pinterest/ktlint/releases/download/$version/ktlint"

# Set the destination directory and file name
destination_dir="/tmp"
file_name="ktlint-$version"

mkdir -p $destination_dir



# Check if the file already exists in the destination directory
if [ ! -e "$destination_dir/$file_name" ]; then
  if command -v curl >/dev/null 2>&1; then
    curl -LJO "$url"
    mv "ktlint" "$destination_dir/$file_name"
  elif command -v wget >/dev/null 2>&1; then
    wget -O "$destination_dir/$file_name" "$url"
  else
    echo "Error: curl or wget not found. Please install either curl or wget."
    exit 1
  fi

  chmod +x "$destination_dir/$file_name"
fi

should_format=true
for arg in "$@"; do
  if [ "$arg" == "--no-format" ]; then
    should_format=false
    set -- "${@//--no-format/}"
    break
  fi
done

check_support=false
for arg in "$@"; do
  if [ "$arg" == "--check-support" ]; then
    check_support=true
    set -- "${@//--check-support/}"
    break
  fi
done

args=()

if [ "$should_format" = true ]; then
  args+=("--format")
fi

args+=("$@")

if [ "$check_support" = true ]; then
  cd .support
  "../$destination_dir/$file_name" **/*.kt **/*.kts \!**/build/** \!Dangerfile.df.kts --color --color-name=YELLOW "${args[@]}"
else
  "$destination_dir/$file_name" **/*.kt **/*.kts \!**/build/** \!Dangerfile.df.kts --color --color-name=YELLOW "${args[@]}"
fi

