name: Check

on:
  pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Danger
        uses: danger/kotlin@1.3.3
        with:
          dangerfile: .github/Dangerfile.df.kts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: .github/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      # if this doesn't exist the configuration cache has problems that cause tests to fail
      - name: Create cache directory
        run: mkdir -p ~/.config/.android/cache

      - name: Run build task
        run: ./gradlew build

      - name: Upload build reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            **/build/reports/
            **/build/test-results/

  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: .github/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Run detekt
        run: ./gradlew detekt detektMain

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run ktlint
        run: ./format --no-format

  abi_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: .github/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Check ABI compatibility
        run: ./gradlew checkLegacyAbi

      - name: 'Notify on failure'
        if: failure()
        run: echo "ABI check failed. Run ./gradlew updateLegacyAbi to fix."

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx16g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m"
